### ISSUE TITLE
Switching between ROMs with a saved state freezes XBSX2

### ISSUE THREAD

**Issue by 2ndMessiah** [EmulationCollective/XBSX2#13]
**Describe the bug**

Open a ROM then quit the ROM, and try to open another one with a saved state(Or even default boot) would make the latest XBSX2 freeze in pure black screen. 

Sometimes it'll crash into the dev home, and sometimes it will stay on the black screen forever.

I'll just have to force quit it and open it again. But the worst scenario is that there's a chance xbsx2 wouldn't launch after a force quit (It then crashes on launching). I have to reboot the console then. 

I don't think the previous build had this issue.

**Desktop:**
 - Console: Series S
 - Version 2.0.8.1

**Additional info**

I updated the version from 2.0.8. Not a fresh new installation.

TY dev!

**Comment by SternXD** [comment]
@2ndMessiah I plan to release 2.0.8.2 sometime this weekend when that build comes out I'd like you to retry this.
