### ISSUE TITLE
[BUG]: Wrong Labels on X and Y buttons

### ISSUE THREAD

**Issue by jcnavarro87** [EmulationCollective/XBSX2#16]
### Describe the Bug

It's not a bug, just a wrong Label, on XBSX2.0 V2.0.8.2 UWP Game list

On the lower right side:
X button displays "Change View"
Y button displays "Launcher Options"

Labels are inverted.

### Reproduction Steps

Open game list -> push X to "change game view", but it will open the launch options box

Push Y to supposedly open "launch options" but it will change the game view,

I believe that the labels are wrong. Might be an easy fix.

### Expected Behavior

On game list, lower right side

X button label must be "Launch Options"
Y button label must be "Game View"
 

### PCSX2 Revision

2.0.8.2

### Operating System

Windows 11

**Comment by jcnavarro87** [comment]
> I just tested this on PCSX2, so this is not an XBSX2 issue. fortunately it has just been fixed Once Stern updates XBSX2 to the latest PCSX2 commits, it should be fixed automatically. here some screenshots
> 
> PCSX2 v2.1.227 ![227](https://private-user-images.githubusercontent.com/144561229/380456108-1377a292-f4f5-4519-8bfe-27ce1ee979d3.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDc0OTcsIm5iZiI6MTczMDAwNzE5NywicGF0aCI6Ii8xNDQ1NjEyMjkvMzgwNDU2MTA4LTEzNzdhMjkyLWY0ZjUtNDUxOS04YmZlLTI3Y2UxZWU5NzlkMy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwNTMzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjYxMzk5MWY3YjZjZDlmNzQwMjhhYjUyNTQ2OWY0ZjhiZGYwMmM1YmU5MzU5OTZmM2FmMzRiZGEyMjgxODkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FcY-I9T-d0s1hx49mnixxVyVn3sMfigMk4S3wuYOHhA) PCSX2 v2.1.228 ![228](https://private-user-images.githubusercontent.com/144561229/380456137-d132759c-822c-4ef7-8a29-f640ebbd13b2.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMDc0OTcsIm5iZiI6MTczMDAwNzE5NywicGF0aCI6Ii8xNDQ1NjEyMjkvMzgwNDU2MTM3LWQxMzI3NTljLTgyMmMtNGVmNy04YTI5LWY2NDBlYmJkMTNiMi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwNTMzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGU1NTk2ZDhiYWI4YzFmZjgzNmFjMjJlNzU3NDk0OGQzNjIwYzk5MTI0NGMxMmEzYjVhNmQ4NDQ1OTcxMDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gPxlnVfrwDoUVOiKxt-RUpnEz5Q6AR2wKX6r5uzpCVU)

Awesome, thank you!

**Comment by SternXD** [comment]
Update will be out once I have people test it then I'll make a public release.
