### ISSUE TITLE
[Feature Request]: Mesa support?

### ISSUE THREAD

**Issue by RollPlayStation** [EmulationCollective/XBSX2#19]
### Description

I'd love to see Mesa get implemented at some stage.

### Reason

Switching to Vulkan would likely benefit some PS2 games' visuals.

### Examples

Sega Model 3 emulator on Series X

**Comment by SternXD** [comment]
I currently have no plans to address this, as my primary testing device is an Xbox One X, which doesn’t support Mesa. I won’t be able to work on this until I have access to an Xbox Series S. Additionally, Vulkan isn’t supported on Xbox only OpenGL via Mesa is available at this time.
