### ISSUE TITLE
[BUG]: replacements issue for Burnout revenge and Burnout 3

### ISSUE THREAD

**Issue by zecaodopneu** [EmulationCollective/XBSX2#6]
### Describe the Bug

Enabling replacements in Burnout revenge garage or anywhere in Burnout 3:Takedown crashes the game, it's a normal crash that sends you back to xbox dev home

### Reproduction Steps

Start the game with replacements activated, or enabling it in the middle of a race, Burnout revenge supports replacements in menu somehow

### Expected Behavior

Replacements working in these two games

### PCSX2 Revision

Xbsx2.0.7

### Operating System

Windows 11

### CPU

Xbox series s 

### GPU

Xbox series s 

### Emulation Settings

Everything in native didn't worked
Enable texture replacements:on
Asynchronous texture loading: on

**Comment by SternXD** [comment]
Hello, I apologize for the delay in responding. I’m planning to release version 2.0.8.1 later today. Once it’s available, could you please try it on that build?

**Comment by zecaodopneu** [comment]
Sure, no problem.
I made some custom skins for burnout revenge and I will try it

Em ter., 27 de ago. de 2024, 14:44, Stern ***@***.***>
escreveu:

**Comment by zecaodopneu** [comment]
Man, I tested xbsx2.0.8.1 and the replacements bug is there still

Em ter., 27 de ago. de 2024, 14:44, Stern ***@***.***>
escreveu:

**Comment by tangomike99** [comment]
I am also experiencing this issue. Any game that has replacement textures enabled and available will crash the application within a few seconds of loading the game. Other games appear to work fine.

**Comment by tangomike99** [comment]
Here's some additional context on this issue in terms of XBSX2. I am not sure if it is helpful.

Replacement textures last worked in release v2.0.2 ([linked here](https://github.com/SirMangler/pcsx2/releases/tag/2.0.2)).
Replacement textures were broken in release v2.0.3 and have not worked since then ([linked here](https://github.com/SirMangler/pcsx2/releases/tag/2.0.3)).

Related issue from that other repo: https://github.com/SirMangler/pcsx2/issues/24.

**Comment by tangomike99** [comment]
As of release 2.0.8.2, this issue is still present.
Enabling replacement textures causes XBSX2 to crash.

**Comment by SternXD** [comment]
> As of release 2.0.8.2, this issue is still present. Enabling replacement textures causes XBSX2 to crash.

Currently, I don’t have a fix for this issue. Resolving it would require several hours of work, which I don’t have the time for at the moment. As such, I’m closing this for now. When I’m able to revisit the issue, I’ll reopen it. In the meantime, I’ll take a look at the precache texture problem.

**Comment by tangomike99** [comment]
@SternXD, understood. Could I provide any assistance or information for this, such as error logs?

**Comment by SternXD** [comment]
Update: I have determined the issue with Texture Replacements are related to the use of .png packs I would recommend moving to .dds as those don't seem to have any issues as of the time of my testing on 2.0.8.2.
